# Generated by Django 2.1.3 on 2018-11-07 09:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('houseNumber', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('houseStreet', models.CharField(max_length=255)),
                ('postalCode', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=128)),
                ('firstName', models.CharField(max_length=128)),
                ('birthDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='customers.Customer')),
                ('contractNumber', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Address'),
        ),
    ]
