# Generated by Django 2.1.3 on 2018-11-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='civilite',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
